### ISSUE TITLE
No media_player after installation and config

### ISSUE THREAD

**Issue by elgeniskogen** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#21] opened 2022-01-21 14:23 UTC
Hi,

Thanks for doing this great work and for sharing! I hope you enjoyed the coffee and are able to help me.

I have a Samsung HW-Q960A (think same as 950 in US) installed and running fine in SmartThings app. I am able to use the SmartThings integration and access all my devices in SmartThings. For the Soundbar I can only see status and turn on/Off, so I installed your component with HACS. I have booted HA after install in HACS and after config, but the media_player don´t show up among the entities. I have turned on debug-logging for custom_components.smartthings_soundbar, but there are no messages in the log. 

My configuration.yaml is liek this

```
media_player:
  - platform: smartthings_soundbar
    name: Soundbar
    api_key: "fcd9983f-fb9d-4d91-b939-XXXXXXXXXXXX"
    device_id: "93e650eb-9e34-f161-8667-XXXXXXXXXXXXX"

logger:
  default: warning
  logs:
    custom_components.smartthings_soundbar: debug

```

If I am not able to select input-source with your great component, I am afraid I will have to retrun the soundbar. So your help will be highly appreacted!!!

best regards

Erik :-)

**Comment by PiotrMachowski** [comment] 2022-01-21 14:37
Are you sure there is absolutely nothing in logs? It might be just after HA start

**Comment by elgeniskogen** [comment] 2022-01-21 14:39
The only mention of the integation in the log is:

````
2022-01-21 15:30:30 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration smartthings_soundbar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by PiotrMachowski** [comment] 2022-01-21 15:34
I have checked the code and there should be an entity even when communication with SmartThings fails... Can you check your config again?

By the way, this integration is really poorly implemented, I have also a [fork of built-in SmartThings integration](https://github.com/PiotrMachowski/Home-Assistant-test-components-SmartThings) that adds support for media players, but it is not up to date with the latest HA version. I will try to add it officially to HA (hopefully soon)

**Comment by elgeniskogen** [comment] 2022-01-21 16:11
Thanks for following up! 

There's is absolutely no entity for the sounder :-) I have tried a gazillion times and checked. 

I tried the exact same config on another instance for HA (with with 2021.12.09 instead of 2021.12.10) and the it works perfectly! I have also tried the script and it output:

```
STATUS
{'main': {'mndt': {'value': '2021-01-01'}, 'mnfv': {'value': 'HW-Q960AWWB-1010.1'}, 'role': {'value': None}, 'mnhw': {'value': ''}, 'detailName': {'value': ''}, 'data': {'value': None}, 'di': {'value': 'DEVICE_ID'}, 'supportedPlaybackCommands': {'value': '["play","pause","stop"]'}, 'supportedInputSources': {'value': '["digital","HDMI1","bluetooth","HDMI2","wifi"]'}, 'mnsl': {'value': ''}, 'dmv': {'value': 'res.1.1.0,sh.1.1.0'}, 'switch': {'value': 'on'}, 'mode': {'value': '25'}, 'vid': {'value': 'VD-NetworkAudio-002S'}, 'mnpv': {'value': '5.5'}, 'icv': {'value': 'core.1.1.0'}, 'st': {'value': '1970-01-01T00:00:31Z'}, 'totalTime': {'value': '0'}, 'playbackStatus': {'value': 'stopped'}, 'mute': {'value': 'unmuted'}, 'n': {'value': 'Samsung Soundbar Q960A'}, 'volume': {'value': '0', 'unit': '%'}, 'mnmo': {'value': 'HW-Q960A'}, 'mnmn': {'value': 'Samsung Electronics'}, 'mnml': {'value': ''}, 'mnos': {'value': 'Tizen'}, 'pi': {'value': 'DEVICE_ID'}, 'inputSource': {'value': 'wifi'}, 'masterName': {'value': None}, 'status': {'value': None}, 'audioTrackData': {'value': '{"title":"NRK P1 Oslo og Akershus","artist":"","album":""}'}, 'elapsedTime': {'value': '0'}}}

```

I am now updating the second instance to 2021.12.10 as well to see if it that version making problems. If it still works on second instance HA, I am lost in what could be wrong with the main instance of HA. All other HACS components etc work fine.

Would be FANTASTIC of the built in integration could have media player added :-)

Thanks again for your support!! :-)

**Comment by elgeniskogen** [comment] 2022-01-21 22:51
@PiotrMachowski  I have updated my previous comment to reflect the fact the the second HA instance also work with 2021.12.10. No I am lost on where to move next......

**Comment by PiotrMachowski** [comment] 2022-01-21 22:58
@elgeniskogen Maybe there is a problem in configuration file that results in ignoring this media_player entry?

**Comment by PiotrMachowski** [comment] 2022-01-24 05:01
@elgeniskogen Have you found the root of your problem?

I will close this issue now, as it doesn't seem it is caused by the integration's code.

**Closed by PiotrMachowski** 2022-01-24 05:01 UTC

**Comment by elgeniskogen** [comment] 2022-01-24 08:37
Now it is working :-) My bad, as I had two media_player keys in the config :-( Sorry!!
