### ISSUE TITLE
Samsung HW-Q990D not supported yet? :-)

### ISSUE THREAD

**Issue by LJ-Stevo** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#71] opened 2024-07-25 10:23 UTC
Hi,

Just asking as a noob, is it possible to add support for the newest model HW-Q990D?
At the moment I figured out to get the entity.
Now I only have:
On/Off
Play/Pause
Mute/Unmute
Volume + / Volume - (with volume bar)

Thanks!

**Comment by PiotrMachowski** [comment] 2024-09-20 16:56
@LJ-Stevo @Greg-or-y 

Can you show the state and attributes of entity that is created?

[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Comment by Greg-or-y** [comment] 2024-09-20 17:48
![image](https://github.com/user-attachments/assets/6b2ed50e-9a7f-4ad5-90d4-23f9b9e33025)

![image](https://github.com/user-attachments/assets/b2295955-c09c-411e-bd80-20087c8a9398)

**Comment by Greg-or-y** [comment] 2024-09-20 17:52
Działa  tylko  głośniej/ciszej  i  mute.  brak  wyboru wejścia (na dole pierwszego screena)

**Comment by Greg-or-y** [comment] 2024-09-20 17:53
Nie widzę też wartości  liczbowej  określającej aktualny poziom   głośności, co jest przydatne w  automatyzacji.

**Comment by Greg-or-y** [comment] 2024-09-20 17:57
![image](https://github.com/user-attachments/assets/3ae29781-ecb5-40d7-a793-de22072e4c3b)

**Comment by PiotrMachowski** [comment] 2024-09-20 18:13
coś w logach jest?

**Comment by Greg-or-y** [comment] 2024-09-20 18:24
![image](https://github.com/user-attachments/assets/072ba633-e0d1-4aee-8fb4-62370da0e5cd)

**Comment by PiotrMachowski** [comment] 2024-09-20 18:40
Do you have built-in Smartthings integration configured?

**Comment by unlobito** [comment] 2024-11-03 21:01
Hey @PiotrMachowski,

I'm having similar trouble with a HW-Q930D (2024).

I get the same error as @Greg-or-y in the Home Assistant log.

<details>
<summary>Update for media_player.q_series_soundbar fails</summary>

> Logger: homeassistant.helpers.entity
Source: helpers/entity.py:942
First occurred: 20:52:39 (1 occurrences)
Last logged: 20:52:39
Update for media_player.q_series_soundbar fails

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_soundbar/media_player.py", line 68, in update
    SoundbarApi.device_update(self)
  File "/config/custom_components/smartthings_soundbar/api.py", line 39, in device_update
    playback_state = data['main']['playbackStatus']['value']
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'playbackStatus'
```
</details>

Similar to @LJ-Stevo, I'm also only presented with power, play/pause, volume up/down, and no volume level.

<details>
<summary>State: media_player.q_series_soundbar</summary>

> State: on

```
volume_level: 1
is_volume_muted: false
media_title: 
source: 
device_class: speaker
friendly_name: Q-Series Soundbar
supported_features: 85389
```
</details>

The built-in SmartThings integration (using a separate API key with identical permissions) is able to show the current input and volume level, in addition to emitting a power switch at `switch.q_series_soundbar`.

<details>
<summary>States: sensor.q_series_*</summary>

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/c39c0cd8-4b31-4b2d-a49a-a9998b76d5a5">
</details>

I'm happy to provide any other details that could assist with debugging.

Thanks for your work on this integration :)

**Comment by mckochan** [comment] 2024-11-19 19:30
Same error with HE-LS60D music frame.

**Comment by MarekMarcinski** [comment] 2024-11-23 06:40
@PiotrMachowski below you can find a response looks like for a GET req to this endpoint: https://api.smartthings.com/v1/devices/dev_id/states
I think the problem is that they removed playbackStatus from main node.
`{
    "main": {
        "logType": {
            "value": "[\"errCode\",\"dump\"]"
        },
        "mndt": {
            "value": "2024-01-01"
        },
        "mnfv": {
            "value": "SAT-MT8532D24WWC-1016.0"
        },
        "role": {
            "value": null
        },
        "mnhw": {
            "value": ""
        },
        "detailName": {
            "value": "External Device"
        },
        "data": {
            "value": null
        },
        "di": {
            "value": "xxx-xxx-xxx-xxx"
        },
        "supportedInputSources": {
            "value": "[\"digital\",\"HDMI1\",\"bluetooth\",\"wifi\",\"HDMI2\"]"
        },
        "supportedWiFiFreq": {
            "value": "[\"2.4G\",\"5G\"]"
        },
        "mnsl": {
            "value": ""
        },
        "dmv": {
            "value": "res.1.1.0,sh.1.1.0"
        },
        "tsId": {
            "value": "VD02"
        },
        "switch": {
            "value": "off"
        },
        "dumpType": {
            "value": "file"
        },
        "mode": {
            "value": "10"
        },
        "vid": {
            "value": "VD-NetworkAudio-003S"
        },
        "endpoint": {
            "value": "PIPER"
        },
        "mnpv": {
            "value": "8.0"
        },
        "icv": {
            "value": "core.1.1.0"
        },
        "mediaOutputSupported": {
            "value": null
        },
        "autoReconnection": {
            "value": "true"
        },
        "st": {
            "value": "1970-01-01T00:00:44Z"
        },
        "updatedTime": {
            "value": "1732343424"
        },
        "minVersion": {
            "value": "3.0"
        },
        "wifiUpdateSupport": {
            "value": "true"
        },
        "executableServiceList": {
            "value": null
        },
        "setupId": {
            "value": "301"
        },
        "supportedAuthType": {
            "value": "[\"OPEN\",\"WEP\",\"WPA-PSK\",\"WPA2-PSK\",\"EAP\",\"SAE\",\"OWE\",\"FT-PSK\"]"
        },
        "mobileCamSupported": {
            "value": null
        },
        "mute": {
            "value": "unmuted"
        },
        "protocolType": {
            "value": "ble_ocf"
        },
        "n": {
            "value": "Q-Series Soundbar"
        },
        "mnId": {
            "value": "0AJK"
        },
        "volume": {
            "value": "15",
            "unit": "%"
        },
        "mnmo": {
            "value": "HW-Q990D"
        },
        "mnmn": {
            "value": "Samsung Electronics"
        },
        "imeAdvSupported": {
            "value": null
        },
        "mnml": {
            "value": ""
        },
        "mnos": {
            "value": "Tizen"
        },
        "signinPermission": {
            "value": null
        },
        "pi": {
            "value": "xxxx-xxxx-xxxx"
        },
        "inputSource": {
            "value": "digital"
        },
        "status": {
            "value": "Idle"
        }
    }
}`

**Comment by TTLucian** [comment] 2024-12-23 14:04
Same as https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/issues/71#issuecomment-2453575704
Soundbar HW-Q930D. Should I open another issue?

**Comment by PiotrMachowski** [comment] 2024-12-30 06:47
Should be fixed in [v1.0.5](https://github.com/PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar/tree/v1.0.5)

**Closed by PiotrMachowski** 2024-12-30 06:47 UTC

**Comment by unlobito** [comment] 2024-12-31 00:36
@PiotrMachowski can confirm this fixes things on my end- thanks for your work on this! 🚀

**Comment by TTLucian** [comment] 2024-12-31 03:57
It's also kinda working for me on Q930D but I changing source does nothing and it's missing TV/ARC source.

**Comment by PiotrMachowski** [comment] 2024-12-31 03:58
@TTLucian is that a downgrade compared to previous version?

**Comment by TTLucian** [comment] 2024-12-31 04:00
Nope. Previous version was not working at all. Not even the volume

**Comment by PiotrMachowski** [comment] 2024-12-31 04:30
Can you show state and attributes of soundbar entity from dev tools?

**Comment by TTLucian** [comment] 2024-12-31 04:35
```yaml
source_list:
  - D.IN
  - HDMI1
  - BT
  - WIFI
volume_level: 0.1
is_volume_muted: false
source: D.IN
device_class: speaker
friendly_name: Soundbar
supported_features: 85389
```
The current source is TV/ARC but it's missing. 
I can't find anything in HA logs. Not even with debug log enabled.

**Comment by Greg-or-y** [comment] 2025-01-01 09:41
Cześć Piotrze, 

Przepraszam zniknąłem na jakiś czas.
Dziś podniosłem integrację do 1.0.5 , mam listę wejść ale wybieranie z niej czegokolwiek po prostu nie przełącza wejść / nie działa. 

Czy mogę coś zrobic (diagnostyka z mojej strony) aby pomóc rozwiązać problem ? 

Pozdrawiam

**Comment by Greg-or-y** [comment] 2025-01-01 09:51
Dodam tylko, że gdy przełączam źródło z pilota to na liście źródeł w Twojej integracji źródło aktualizuje się prawidłowo,  natomiast jak wybieram inne z drop listy w integracji to nie przełącza wejść w soundbarze.

**Comment by lemval** [comment] 2025-01-01 13:09
I also looked into this. I own a Q930D. The new version shows the input alright (but sometimes the API does not specify the input). Selecting the input via the API doesn't work either... You can test it yourself at https://my.smartthings.com/advanced/devices/<your_device_id> (after you logged on, see instructions for receiving token)
Both samsungvd.audioSoundFrom/setSoundFrom (403 - so need other token) and samsungvd.soundFrom/setSoundFrom (COMPLETED) won't trigger anything. Values possible: 1 / D.IN, 3 / HDMI1, 4 / BT, 25 (TV eARC), 26 / WIFI, 30 / Chromecast built-in

**Comment by PiotrMachowski** [comment] 2025-01-02 03:12
Sometimes it helps to remove the soundbar from SmartThings and add it again... 😒
