### ISSUE TITLE
Feature Request; Change sound mode

### ISSUE THREAD

**Issue by patroza** [PiotrMachowski/Home-Assistant-custom-components-SmartThings-Soundbar#30] opened 2022-07-01 08:48 UTC
HW-Q990/995/950A/T, the ability to change the sound mode (Standard, Surround, Game, Adaptive)

**Comment by PiotrMachowski** [comment] 2022-07-01 09:22
It's not possible using SmartThings API
https://developer-preview.smartthings.com/docs/devices/capabilities/capabilities-reference

Duplicate of #14

**Closed by PiotrMachowski** 2022-07-01 09:22 UTC
